#![forbid(unsafe_code)]

mod commands;

pub fn run() -> tauri::Result<()> {
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![
            commands::get_health,
            commands::send_chat_message,
            commands::cancel_chat_message,
            commands::list_chat_sessions,
            commands::list_chat_messages,
            commands::list_activity,
            commands::list_memory,
            commands::get_memory_history,
            commands::update_memory_state,
            commands::restore_memory_revision,
            commands::list_providers,
            commands::upsert_provider,
            commands::remove_provider,
            commands::test_provider,
            commands::list_models,
            commands::upsert_model,
            commands::get_application_settings,
            commands::update_application_settings,
            commands::get_usage_stats,
            commands::get_diagnostics,
            commands::clear_operational_logs,
            commands::submit_response_feedback,
            commands::confirm_action,
            commands::preview_ai_request,
            commands::get_security_overview,
            commands::update_security_profile,
            commands::list_permission_grants,
            commands::upsert_permission_grant,
            commands::revoke_permission_grant,
            commands::list_resource_labels,
            commands::upsert_resource_label,
            commands::remove_resource_label,
            commands::list_agents,
            commands::upsert_agent,
            commands::remove_agent,
            commands::run_agent,
            commands::list_agent_sessions,
            commands::list_registered_applications,
            commands::upsert_registered_application,
            commands::remove_registered_application,
        ])
        .run(tauri::generate_context!())
}
