[package]
name = "halquen-desktop"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false
license.workspace = true

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
halquen-domain = { version = "0.1.0", path = "../../../crates/domain" }
halquen-memory = { version = "0.1.0", path = "../../../crates/memory" }
halquen-protocol = { version = "0.1.0", path = "../../../crates/protocol" }
serde = { workspace = true }
tauri = { version = "2.11.5", features = [] }

[lints]
workspace = true
